### PR TITLE
Add note about the name

### PR DESCRIPTION
**Pull request by brianloveswords**
I updated my tessel and was mildly surprised when it removed the name I gave it. This adds a line to the docs to be clear that's gonna happen.

### CODE REVIEW

**Comment by wyze** [comment]
Could you capitalize the 2 reference to Tessel please?

**Comment by johnnyman727** [comment]
Thanks for the contribution! Sorry about that surprise. Hopefully we can patch the updater to not be so forgetful sometime soon.

**Comment by Frijol** [comment]
@wyze is this still needed, or did the changes in hostname get resolved?

**Comment by johnnyman727** [comment]
This is fixed as of https://github.com/tessel/openwrt-tessel/pull/59

**Comment by wyze** [comment]
Forgot to come back and close this out after the latest firmware was released.

**Pull request closed without merging**
