### PR TITLE
added an error parameter to the callback function

### PR DESCRIPTION
**Pull request by snollygolly**
I just got my tessel 2, and as I'm going through the tutorial, my code was failing with:

```
ReferenceError: err is not defined
    at null.<anonymous> (/tmp/remote-script/index.js:1:151)
    at emitNone (events.js:67:13)
    at emit (events.js:166:7)
    at Immediate._onImmediate (/tmp/remote-script/node_modules/ir-attx4/index.js:1:715)
    at processImmediate [as _immediateCallback] (timers.js:368:17)
```

It looks like the issue is on line 18 of the tutorial code, it's checking for `err`, but it's never being defined.

### CODE REVIEW

**Comment by LinusU** [comment]
I might be wrong about this, but I don't think that the ready event actually exposes an `err` parameter, so I think that the right thing to do would be to remove it all together

**Comment by rwaldron** [comment]
Nice catch—there is [actually no `err` argument there](https://github.com/tessel/ir-attx4/blob/master/index.js#L90), so the right fix is as @LinusU suggests: remove the usage from the example. Ping me here and I will land it as soon as you update

**Comment by snollygolly** [comment]
Sounds good.  I've removed the parameter from the callback, and removed the check for `err` on the ready event.

@rwaldron look good?

**Comment by rwaldron** [comment]
Perfect! I will merge this now, but @Frijol or @johnnyman727 will do the deployment :)

**Comment by johnnyman727** [comment]
@snollygolly thanks for the contribution! Can you ensure you've signed our [CLA really quick](http://dojofoundation.org/about/claForm)?

**Comment by snollygolly** [comment]
Done!

**Pull request merged**
