### PR TITLE
adds USB storage module tutorial

### PR DESCRIPTION
**Pull request by Frijol**
Adds tutorial for USB mass storage module.

Still needs:
- [x] Example
- [x] GIF of example's results
- [x] Description of results for Step 4
- [x] Bonus problem

### CODE REVIEW

**Comment by johnnyman727** [comment]
We should remove step 3 - that's only a BLE command.

Also, we should tell people where the flash storage was mounted:

``` .js
var fs = require('fs');
var path = require('path');
var mountPoint = '/mnt/sda1';

fs.readFile(path.join(mountPoint, 'myFile.txt'), function(err, contents) {
  ...
});
```

The first flash drive you plug in will be mounted at `/mnt/sda1` and the second will be mounted at `/mnt/sdb1`.

We may also want to note [this corner case](https://github.com/tessel/openwrt-tessel/issues/40)?

**Comment by Frijol** [comment]
mountPount > mountPoint I think in your code above?

**Comment by johnnyman727** [comment]
Yes, thanks.

**Comment by Frijol** [comment]
anyone is welcome to review, @johnnyman727 you can be on point for it if no one else wants to

**Comment by johnnyman727** [comment]
looks great to me!

**Pull request merged**
