### PR TITLE
fixes https://github.com/tessel/t2-start/issues/118

### PR DESCRIPTION
**Pull request by Frijol**
r? @rwaldron

### CODE REVIEW

**Comment by Frijol** [comment]
ping! or @johnnyman727

**Comment by johnnyman727** [comment]
r+

**Comment by rwaldron** [comment]
Sorry I missed this, to be honest I had to think about it just now for a moment as to why this would even be necessary. But then I realized that streaming over a web socket into a browser would, of course, require some kind Wi-Fi connection. 

 Maybe we should make a second tutorial (or just add to the main tutorial?)  that shows what you can do without Wi-Fi, such as taking pictures and storing them on USB storage

**Comment by Frijol** [comment]
that would be cool (..or stored locally on Tessel? I've had people want to do that at workshops)

**Pull request merged**
