### PR TITLE
Only display the blinking and quitting message once.

### PR DESCRIPTION
**Pull request by rwaldron**

### CODE REVIEW

**Comment by LinusU** [comment]
LGTM :+1:

**Comment by Frijol** [comment]
:( I like the many logs. I guess we don't have to have them, but it does make people look- especially with deploy taking so long on T2, it's nice to have something moving on the screen.

**Comment by Frijol** [comment]
Should be cross-linked with https://github.com/tessel/t2-cli/pull/403

**Comment by Frijol** [comment]
I guess I'm ok with this change if y'all prefer

**Comment by rwaldron** [comment]
> it's nice to have something moving on the screen.

I agree, but only when the display is changing for a reason, like displaying values being read or something

**Pull request merged**
