### PR TITLE
typo fix for audio module `ended` event

### PR DESCRIPTION
**Pull request by ducin**

### CODE REVIEW

**Comment by LinusU** [comment]
Hmm `end` is used almost everywhere in Node, it would have been nice if `tessel-av` followed that. Anyhow, that's another discussion :)

LGTM

**Comment by johnnyman727** [comment]
> Hmm end is used almost everywhere in Node, it would have been nice if tessel-av followed that. 

I agree - I think the solution would be to update `tessel-av` API to emit `end`.

**Comment by Frijol** [comment]
Just ran across this, should have been merged in July! @rwaldron can you confirm that this is still the correct syntax?

**Review by rwaldron — APPROVED** [review]
Nice catch!

**Comment by rwaldron** [comment]
> > Hmm end is used almost everywhere in Node, it would have been nice if tessel-av followed that.
> > I agree - I think the solution would be to update tessel-av API to emit end.

But it's not an "end" event in the sense that you're referring to, which is: 

> The 'end' event is emitted when there is no more data to be consumed from the stream.

(https://nodejs.org/api/stream.html#stream_event_end)

I chose "ended", because that's the event that's emitted for HTML audio when the sound's playback has _ended_. This naming was intentional to differentiate _away_ from Node's "end" event.

**Comment by rwaldron** [comment]
@Frijol LGTM!

**Pull request merged**
