### PR TITLE
State that wifi password flag is optional

### PR DESCRIPTION
**Pull request by johnelliott**
see https://github.com/tessel/t2-start/issues/124

### CODE REVIEW

**Comment by HipsterBrown** [comment]
@johnelliott Looks good to me! :+1: 

Thanks for contributing. Do you mind signing [this CLA](http://www.dojofoundation.org/about/claForm)?

**Comment by johnelliott** [comment]
@HipsterBrown yes, I signed the CLA

**Comment by HipsterBrown** [comment]
Rad, thanks! 

Pinging @Frijol for another set of eyes.

**Comment by Frijol** [comment]
Looks great, thanks for finding & fixing that usability issue!

**Pull request merged**
